import { NextResponse } from "next/server";
import connectToDatabase from "@/lib/mongodb";
import Car from "@/models/Car";

export async function GET() {
  try {
    await connectToDatabase();

    await Car.deleteMany({});

    const cars = [
      {
        make: "Porsche",
        model: "911 Carrera",
        year: 2024,
        type: "Sports",
        pricePerDay: 450,
        images: ["/images/sports-car.png"],
        features: ["Leather Seats", "Bluetooth", "Navigation", "Heated Seats"],
        description: "Experience the thrill of a classic sports car with the Porsche 911 Carrera.",
        transmission: "Automatic",
        seats: 2,
        fuelType: "Petrol",
        available: true,
      },
      {
        make: "Porsche",
        model: "Cayenne Turbo",
        year: 2025,
        type: "SUV",
        pricePerDay: 350,
        images: ["/images/suv-adventure.png"],
        features: ["Panoramic Roof", "AWD", "Premium Audio", "Adaptive Cruise"],
        description: "A luxury SUV that delivers sports car performance with everyday practicality.",
        transmission: "Automatic",
        seats: 5,
        fuelType: "Petrol",
        available: true,
      },
      {
        make: "BMW",
        model: "M4 Competition",
        year: 2025,
        type: "Sports",
        pricePerDay: 380,
        images: ["/images/sports-car.png"],
        features: ["Premium Audio", "Sport Exhaust", "Sunroof"],
        description: "A perfect blend of luxury and track-ready performance.",
        transmission: "Automatic",
        seats: 4,
        fuelType: "Petrol",
        available: true,
      },
      {
        make: "BMW",
        model: "X5 M Competition",
        year: 2024,
        type: "SUV",
        pricePerDay: 320,
        images: ["/images/suv-adventure.png"],
        features: ["Massage Seats", "Head-up Display", "B&W Sound", "Night Vision"],
        description: "A high-performance SUV that rules every terrain in comfort.",
        transmission: "Automatic",
        seats: 5,
        fuelType: "Petrol",
        available: true,
      },
      {
        make: "Audi",
        model: "R8 V10 Performance",
        year: 2023,
        type: "Sports",
        pricePerDay: 600,
        images: ["/images/sports-car.png"],
        features: ["Carbon Fiber Trim", "AWD", "Laser Lights"],
        description: "The ultimate supercar experience, powered by a roaring V10 engine.",
        transmission: "Automatic",
        seats: 2,
        fuelType: "Petrol",
        available: true,
      },
      {
        make: "Audi",
        model: "RS6 Avant",
        year: 2025,
        type: "Sedan",
        pricePerDay: 280,
        images: ["/images/luxury-sedan.png"],
        features: ["RS Sport Seats", "Virtual Cockpit", "Sport Exhaust", "Air Suspension"],
        description: "A supercar disguised as a wagon — blistering pace meets daily usability.",
        transmission: "Automatic",
        seats: 5,
        fuelType: "Petrol",
        available: true,
      },
      {
        make: "Mercedes-Benz",
        model: "G-Class G63 AMG",
        year: 2024,
        type: "SUV",
        pricePerDay: 500,
        images: ["/images/suv-adventure.png"],
        features: ["Massage Seats", "Off-Road Package", "360 Camera"],
        description: "Iconic luxury SUV that commands attention on any road.",
        transmission: "Automatic",
        seats: 5,
        fuelType: "Petrol",
        available: true,
      },
      {
        make: "Mercedes-Benz",
        model: "S-Class S580",
        year: 2025,
        type: "Luxury",
        pricePerDay: 420,
        images: ["/images/luxury-sedan.png"],
        features: ["Executive Seats", "Burmester 3D", "Ambient Lighting", "Champagne Fridge"],
        description: "The pinnacle of automotive luxury — chauffeured elegance at its finest.",
        transmission: "Automatic",
        seats: 5,
        fuelType: "Petrol",
        available: true,
      },
      {
        make: "Mercedes-Benz",
        model: "EQS 450+",
        year: 2024,
        type: "Luxury",
        pricePerDay: 340,
        images: ["/images/electric-car.png"],
        features: ["Hyperscreen", "Zero Emission", "Air Suspension", "4-Zone Climate"],
        description: "All-electric luxury flagship with a breathtaking Hyperscreen dashboard.",
        transmission: "Automatic",
        seats: 5,
        fuelType: "Electric",
        available: true,
      },
      {
        make: "Ford",
        model: "Mustang GT",
        year: 2024,
        type: "Sports",
        pricePerDay: 250,
        images: ["/images/convertible-car.png"],
        features: ["V8 Engine", "Convertible Top", "Track Mode", "B&O Sound"],
        description: "American muscle icon with a howling V8 and drop-top freedom.",
        transmission: "Manual",
        seats: 4,
        fuelType: "Petrol",
        available: true,
      },
      {
        make: "Toyota",
        model: "Land Cruiser 300",
        year: 2025,
        type: "SUV",
        pricePerDay: 220,
        images: ["/images/pickup-truck.png"],
        features: ["4WD", "Diff Lock", "KDSS", "Multi-Terrain Select"],
        description: "Go anywhere, do anything — the ultimate overlanding companion.",
        transmission: "Automatic",
        seats: 7,
        fuelType: "Diesel",
        available: true,
      },
      {
        make: "Tesla",
        model: "Model S Plaid",
        year: 2025,
        type: "Sedan",
        pricePerDay: 360,
        images: ["/images/electric-car.png"],
        features: ["Plaid Mode", "Autopilot", "Glass Roof", "17-inch Display"],
        description: "Electric hyper-sedan with mind-bending acceleration and cutting-edge tech.",
        transmission: "Automatic",
        seats: 5,
        fuelType: "Electric",
        available: true,
      },
    ];

    await Car.insertMany(cars);

    return NextResponse.json({ message: "Seed successful", count: cars.length });
  } catch (error: any) {
    console.error("Seed error:", error);
    return NextResponse.json({ error: "Failed to seed data" }, { status: 500 });
  }
}
